# Generated by Django 4.1.5 on 2023-02-05 12:13

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_postcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(null=True, upload_to=event.models.image_upload_to),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
