# Generated by Django 4.1.5 on 2023-02-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_post_img_delete_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='view_cnt',
            field=models.SmallIntegerField(default=0),
        ),
    ]
