# Generated by Django 4.1.5 on 2023-02-05 14:14

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_view_cnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to=event.models.image_upload_to),
        ),
    ]
