# Generated by Django 4.1.5 on 2023-02-03 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import event.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('location_tags', models.CharField(max_length=128, verbose_name='지역태그')),
                ('content', models.TextField(default='', verbose_name='내용')),
                ('title', models.CharField(max_length=256, verbose_name='제목')),
                ('deadline', models.DateTimeField(verbose_name='마감날짜')),
                ('participants_limit', models.SmallIntegerField(verbose_name='참여인원 제한 수')),
                ('start_event', models.CharField(max_length=50, verbose_name='이벤트 시작일')),
                ('end_event', models.CharField(max_length=50, verbose_name='이벤트 종료일')),
                ('event_imgage', models.ImageField(upload_to=event.models.image_upload_to)),
                ('category', models.CharField(choices=[('운동', '운동'), ('여행', '여행'), ('문화관람', '문화관람'), ('게임', '게임'), ('음악', '음악'), ('사교/인맥', '사교/인맥'), ('봉사', '봉사'), ('자유주제', '자유주제')], default='자유주제', max_length=20)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='태그')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
