# Generated by Django 4.1.5 on 2023-02-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[(0, '운동'), (1, '여행'), (2, '문화관람'), (3, '게임'), (4, '음악'), (5, '사교/인맥'), (6, '봉사'), (7, '자유주제')], default=7, max_length=20),
        ),
    ]
