# Generated by Django 4.1.5 on 2023-01-25 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False, verbose_name='이메일')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('name', models.CharField(max_length=64, verbose_name='이름')),
                ('nickname', models.CharField(max_length=50, verbose_name='닉네임')),
                ('birth', models.CharField(max_length=20, verbose_name='생년월일')),
                ('address', models.CharField(max_length=128, verbose_name='거주지역')),
                ('is_staff', models.BooleanField(default=False, verbose_name='관리자여부')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(default='profile/default.png', upload_to='profile/', verbose_name='프로필이미지')),
                ('participations_cnt', models.SmallIntegerField(verbose_name='참여횟수')),
                ('post_cnt', models.SmallIntegerField(verbose_name='게시글 수')),
                ('comment_cnt', models.SmallIntegerField(verbose_name='댓글 수')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
        ),
    ]
