# Generated by Django 4.1.5 on 2023-02-06 18:36

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='profile-upload/default.png', upload_to=user.models.image_upload_to, verbose_name='프로필이미지'),
        ),
    ]
